OT-DeploySettingsMicroservice | Deployed settings microservice and database onto a Kubernetes cluster
Off-Top-App/SettingsService pull request #6
Opened 2020-07-12 00:26 UTC by frlzjosh

**What I Did:**
1. Created several deployment scripts for the settings microservice as well as the database.
2. Ran these deployment scripts to deploy our microservice and database onto a Kubernetes cluster

**How To Test**
1. Follow this documentation to set up a Kubernetes cluster through minikube
2. Run these commands below in the order seen:
```
kubectl 
```
3. Then you will need to receive the URL that our service is running on in Kubernetes. You can do that through this command: 
- `minikube service settings-service --url`
- Copy and paste that command IP and port into postman and do a GET request to an endpoint `http:<service-url> /api/userSettings/ping` and you should see a response of "

2020-07-14 06:12 UTC, tonynguyen98 requested changes
Very good work! Was able to replicate the cluster on my machine. Just update the documentation to what was done during the meeting

2020-07-14 06:12 UTC, tonynguyen98 commented on kubernetes-deployments/settings-db-secret.yml
> +  MYSQL_ROOT_PASSWORD: password
Remove these from DockerHub

2020-07-14 07:35 UTC, frlzjosh commented on kubernetes-deployments/settings-db-secret.yml
> +  MYSQL_ROOT_PASSWORD: password
done!

2020-07-19 21:54 UTC, tonynguyen98 approved these changes
Great work! I was able to replicate it on my machine after the changes

2020-07-19 21:58 UTC, tonynguyen98 approved these changes
Great work!

2020-07-19 21:59 UTC, tonynguyen98 approved these changes
Let's see if we can merge now

2020-07-19 22:04 UTC, tonynguyen98 approved these changes

2020-07-19 22:18 UTC, merged